### ISSUE TITLE
Links não funcionam em www.pythonfloripa.org

### ISSUE THREAD

**Issue by eliasdorneles** [PythonFloripa/pythonfloripa.github.io#10]
Acessando a página via: http://www.pythonfloripa.org, a página http://pythonfloripa.github.io tá sendo carregada via frame, e nenhum dos links funcionam (aparentemente por causa da Same Origin Policy).

Usando Chrome, no console Javascript aparece o erro:

```
Refused to display 'https://github.com/PythonFloripa/pythonfloripa.github.io' in a frame because it set 'X-Frame-Options' to 'deny'.
```

Acredito que a solução seja evitar os frames e [configurar o redirecionamento no nível de DNS](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/).

/cc @ssjunior @feliperuhland

**Comment by danimaribeiro** [comment]
Que tal um target="_blank" nos links :)

**Comment by eliasdorneles** [comment]
@danimaribeiro hm, muita gambiarra abrir em nova aba/janela todos os links duma página:

1) a navegação em si não é a fonte do problema (frames em um domínio diferente com header `X-Frame-Options: deny`) e,
2) não é o comportamento esperado pelo usuário (quebra o botão Voltar).

eu voto em tentar acertar o HTTP header (se realmente quiserem manter os frames) ou redirecionar no nível DNS (melhor).

**Comment by danimaribeiro** [comment]
Geralmente site externo se abre em nova aba, que é o caso aqui. Os links internos estão funcionando normalmente, pelo menos no meu último teste (chrome).

-----Mensagem Original-----
De: "Elias Dorneles" notifications@github.com
Enviada em: ‎20/‎09/‎2015 16:11
Para: "PythonFloripa/pythonfloripa.github.io" pythonfloripa.github.io@noreply.github.com
Cc: "Danimar Ribeiro" danimaribeiro@gmail.com
Assunto: Re: [pythonfloripa.github.io] Links não funcionam em www.pythonfloripa.org (#10)

@danimaribeiro hm, muita gambiarra abrir em nova aba/janela todos os links duma página:
1) a navegação em si não é a fonte do problema (frames em um domínio diferente com header X-Frame-Options: deny) e,
2) não é o comportamento esperado pelo usuário (quebra o botão Voltar).
eu voto em tentar acertar o HTTP header (se realmente quiserem manter os frames) ou redirecionar no nível DNS (melhor).

**Comment by eliasdorneles** [comment]
`www.pythonfloripa.org` num tá mais funfando.

Talvez a gente pode manter a coisa lean e marketar o endereço do github mesmo? :)

**Comment by feliperuhland** [comment]
@eliasdorneles se adicionarmos o CNAME na branch master (após build no travis) conseguimos acessar com http://floripa.sc.python.org.br/ ou http://florianopolis.sc.python.org.br/

**Comment by feliperuhland** [comment]
Putz, só dá pra usar um.

> Ensure you only have one domain listed in your CNAME file. If you wish to have multiple domains pointing to the same Pages, you will need to set up redirects for the other domains. Most domain registrars and DNS hosts offer this service to their customers.

**Comment by eliasdorneles** [comment]
Floripa it is! :)

**Comment by feliperuhland** [comment]
Consegues fazer o build do travis criar o arquivo CNAME? No almoço eu tento.

**Comment by eliasdorneles** [comment]
hm, não é caso de só mover o CNAME pro diretório docs?

**Comment by eliasdorneles** [comment]
@feliperuhland acho que sim, o próprio mkdocs faz isso: https://github.com/mkdocs/mkdocs/blob/master/docs/CNAME

**Comment by eliasdorneles** [comment]
feito (desculpa o barulho)

**Comment by feliperuhland** [comment]
Sensacional! Valeu @eliasdorneles.
