### ISSUE TITLE
Sugestões de palestras

### ISSUE THREAD

**Issue by feliperuhland** [PythonFloripa/pythonfloripa.github.io#13]
- Como lidar com bytes, texto e erros de unicode
- Truques do IPython
- Introdução à biblioteca mock
- Introdução ao seu módulo preferido da stdlib (exemplos: collections, contextlib, argparse, subprocess, heapq, functools, itertools, weakref, Queue -- qualquer um desses dá uma palestra legal =))
- Introdução ao SQLAlchemy
- Refatorando código Python
- Portando código de Python 2 para Python 3
- BDD com Python
- Como escrever mensagens de erro úteis

**Comment by jairojair** [comment]
Acho que além de coisas básicas em python, algumas dicas básicas em alguns frameworks como Django, Flask ... Abrindo espaço pra perguntas :)

**Comment by eliasdorneles** [comment]
Posso apresentar a "Como escrever mensagens de erro úteis" -- já tenho algumas notas a respeito. :)

**Comment by guilhermemaba** [comment]
@danimaribeiro podemos contar com sua apresentação sobre "machine learning e o IPython" para próximo encontro?

**Comment by danimaribeiro** [comment]
Pode sim, uns 20 minutos de apresentação eu faço.

**Comment by jairojair** [comment]
:+1:

**Comment by jairojair** [comment]
Queria uns 10 minutos pra falar como foi a apresentação do Workshop na UNISUL, e como a galera recebeu Python :)

**Comment by guilhermemaba** [comment]
@jairojair :+1:

**Comment by feliperuhland** [comment]
@jairojair lógico.
