### ISSUE TITLE
Link pro Slack

### ISSUE THREAD

**Issue by mrprompt** [PythonFloripa/pythonfloripa.github.io#27]
Seria legal um "slack-in" da vida, para facilitar a entrada no Slack.

**Comment by jairojair** [comment]
@mrprompt atualizamos o site e focamos no telegram, pois é mais ativo na comunidade.

Entra lá https://telegram.me/joinchat/ENU02wm2sfNRgVO4bxXVzw

Abraço valeu 👍

**Comment by mrprompt** [comment]
ah beleza, valeu @jairojair
