### ISSUE TITLE
Sugestões de templates pro site

### ISSUE THREAD

**Issue by jairojair** [PythonFloripa/pythonfloripa.github.io#5]
Grupo-DF
http://df.python.org.br
https://github.com/grupydf/grupydf.github.io

**Comment by eliasdorneles** [comment]
@jairojair Curti o template, +1.
Só acho que antes de mudar o template, seria legal automatizar a geração do site atual a partir dos fontes.
A não ser que refaçamos o site atual mesmo, mas gostaria dum feedback do @feliperuhland.

@feliperuhland olhei lá no seu fork e não achei o branch com sources (`master` e `gh-pages` estão com HTML compilado). Faltou um push?

/cc @ssjunior 

Valeu rapazes!

**Comment by feliperuhland** [comment]
@eliasdorneles hoje à noite vou dar push do projeto e te aviso, pode ser?

**Comment by jairojair** [comment]
Vão precisar de ajuda em algo ?

**Comment by eliasdorneles** [comment]
@feliperuhland beleza!

@jairojair seria legal permissão de admin pro repo pra configurar build no Travis e tal. =)

Bem, por enquanto o plano é só atualizar o conteúdo e automatizar atualização do site atual: colocar os fontes mkdocs aqui, configurar build no Travis pra compilar o site estático e publicar quando pushar no branch dos sources.

Não sei se nesse primeiro passo precisa de muita ajuda além das permissões, mas o objetivo é deixar fácil pra outras pessoas contribuírem (e pros mantenedores revisarem).

Então, pra revisar e mergear as próximas contribuições (atualizações no tema, conteúdo, etc), enfim, para os passos seguintes, com certeza vai ser legal ter ajuda. :+1:

**Comment by feliperuhland** [comment]
@eliasdorneles fiz um merge para uma branch chamada development.

Qualquer coisa, é só falar!

**Comment by eliasdorneles** [comment]
beleza, valeu @feliperuhland -- amanhã de noite vou dar uma fuçada!

**Comment by eliasdorneles** [comment]
Tô apanhando pra fazer o build funcionar: https://travis-ci.org/PythonFloripa/pythonfloripa.github.io/builds/78842852 :/

**Comment by eliasdorneles** [comment]
Woohoo, deploy com auto-update tá funcionando agora: https://travis-ci.org/PythonFloripa/pythonfloripa.github.io/builds/79144323 =)

Qualquer novo commit no branch development vai disparar a atualização do master automática.
Dessa forma, qualquer pessoa pode mandar pull request para o branch de development, e basta mergear a pull request para atualizar o site.

Coisas que é legal vcs saberem:

1) gerei a chave de deploy localmente com `ssh-keygen` e adicionei com permissão de escrita
2) encriptei localmente usando o [travis encrypt-file](http://docs.travis-ci.com/user/encrypting-files/)
3) a atualização automática tá [forçando o push (`--force`)](https://github.com/PythonFloripa/pythonfloripa.github.io/blob/development/deploy.sh#L22), workaround pra evitar conflitos no master

Valeu!

/cc @feliperuhland @ssjunior

**Comment by feliperuhland** [comment]
Coisa linda!

Valeu @eliasdorneles. :beers:
