### ISSUE TITLE
Resgatar conteúdo do site antigo

### ISSUE THREAD

**Issue by eliasdorneles** [PythonFloripa/pythonfloripa.github.io#50]
Olá!

Não sei qual foi exatamente a motivação pra trocar a engine do site, mas me pareceu um pouco precipitado botar no ar o site novo sem o conteúdo do antigo.

Tinha bastante informação interessante no site antigo que tá faltando no site atual.

Sugiro resgatar pelo menos os links mais importantes da comunidade: https://github.com/PythonFloripa/pythonfloripa.github.io/blob/327d782bf1499ca46942c97144927db4f34704e9/docs/comunidade.md

Seria bacana poder guardar a memória dos encontros primeiros encontros também: https://github.com/PythonFloripa/pythonfloripa.github.io/blob/327d782bf1499ca46942c97144927db4f34704e9/docs/encontros.md

**Comment by mateusoliveira43** [comment]
A ideia foi simplificar para atrair iniciantes a contribuir com o site, como falamos um pouco na última edição online.

O links pretendemos colocar sim, foi nossa maior motivação para o site novo! Sera a página "contato" que já criei outra issue.

Para primeira leva de atividades, não pretendemos colocar as partes legadas do site antigo, mas deixamos na história do git justamente para não se perderem!

**Comment by ssjunior** [comment]
@mateusoliveira43 

Como criador e primeiro incentivador da comunidade Python Floripa, acho muito válido novas pessoas se interessarem e assumirem a manutenção e a continuidade do projeto. Você está de parabéns pela iniciativa. Tem todo apoio para continuar. 👏 

Dito isso não acho legal simplesmente sumir com o histórico de tudo que foi feito.

Tem muita gente aqui que tem uma história com esta comunidade, @eliasdorneles (já sinto falta das palestras do mestre) @feliperuhland @jairojair @sergiomario @guilhermemaba  dentre outros que não foram citados, que foram os pilares desta construção.

O conteúdo pode estar desatualizado, mas, simplesmente sumir com o mesmo e colocar uma página nova no ar sem nenhuma informação, não reforça o espírito de comunidade que sempre foi um pilar deste projeto. Tem que respeitar o histórico da comunidade que sempre foi muito ativa e envolvida. 

Agradeço muito a iniciativa e como disse acho muito válido modernizar e atualizar, mas, sem esquecer o histórico e as pessoas que participaram dela. Lembro que tudo sempre foi construído de forma participativa e nunca de forma isolada. Temos que dar espaço para novas cabeças e mantenedores sem esquecer do passado.

@mateusoliveira43 continue com as mudanças, mas, por favor, envolva as pessoas da comunidade, mesmo aquelas que não participaram de eventos recentes, nesta nova fase. Tenho certeza de que todo mundo vai gostar. 👍 

No bom espírito da comunidade Python sugiro que se volte o site original e se abra espaço para um discussão participativa de como deve ser a continuidade deste projeto. E eventualmente abrir uma RFC para definir como deve ser o novo site. Acho que é de bom tom tentar envolver quem está aqui (quem tem histórico ou apenas um sentimento nostálgico) nas mudanças e se ninguém se manifestar, somente assim tomar decisões individuais.

Abs a todos e principalmente à galera das antigas . 😄

**Comment by rougeth** [comment]
Faço peso a importância do histórico e a página de contatos, pois além de conter parte da história da comunidade, mostram que ela ainda segue ativa e também diminui a barreira para entrada de novas pessoas. Para efeitos práticos, @mateusoliveira43, minha sugestão é criar um branch do site antigo e subir com uma url do github.io ou até mesmo v1.floripa.sc.python.org.br (posso ajudar com as configurações do domínio *.python.org.br se precisar). Com o site antigo no ar, podemos colocar os links para as páginas antigas, enquanto o conteúdo não é migrado para o site novo.

Dito isso, não consigo ver como essa mudança no site vai contra o espírito da comunidade, e muito menos como falta de respeito a comunidade. Na minha opinião, é justamente o oposto, são mudanças como essas, tentativas de se atualizar, que ajudam a manter a comunidade viva.

Em comunidades saudáveis, a barreira de participação deve ser mínima. Definir um processo burocrático para sugerir mudança ou envolver pessoas que já nem se quer participam mais da comunidade para aprovação, é inibir qualquer chance de evolução da comunidade, pela comunidade.

Ontem eu fui removido como *owner* na org PythonFloripa aqui no Github, o que **não é um problema**, já que minha participação hoje em dia é bem limitada, mas sei que ninguém das pessoas que estão **liderando** a comunidade, como o @rafaelcalixto, @melissawm ou @mateusoliveira43, nos últimos meses/anos estão com esse papel. Talvez isso não seja um problema ou uma necessidade, mas qualquer forma de gatekeeping deve ser combatido. É imprescindível passar o bastão, de nada adianta pilares bem construídos se não há o que sustentar.

**Comment by ssjunior** [comment]
@rougeth 

Não se começa uma história apagando a que já existe. Normalmente você começa contando o passado para mostrar o futuro. De onde veio e para onde está indo. A partir daí vc dá a narrativa que quiser. 

Como dito acima é muito saudável a iniciativa e o movimento. Ninguém aqui quer criar barreiras, mas, fiquei surpreso ao ver os 6 anos de história serem apagados. Respeito tem a ver com ouvir opiniões antes de apagar algo que foi construído por outras pessoas sem nem sequer dar espaço para opiniões. Não é instituir um processo burocrático. É dar oportunidade para manifestação. Dá espaço, pergunta, não se manifestou toca adiante. Até porque quem não está ativo pode se sentir animado a participar. Esse é o ponto. 

Sim, achei desrespeitosa a forma como foi feita. Concorde ou não é um sentimento meu que só cabe a mim sentir e os outros a respeitar. Eu estava lá. Eu participei. Eu fui a pessoa que incentivou a criação da comunidade aqui. Você não sabe pq não estava lá. As primeiras reuniões fui eu que convoquei e quem participou lembra das rodadas de pizza, chopp e salgadinhos. 

Meu tempo já passou e estou bem com isso. Outras pessoas devem continuar fomentando a comunidade. Sou das antigas, acho que a mudança é bem vinda e deve ser feita, mas, sou contra apagar a história desta comunidade da forma como foi feito.

Abs

**Comment by eliasdorneles** [comment]
Calma, gente! =)

Acho que estamos todos de acordo que é super válido a iniciativa de manter o site (ele tava tristonho de não ser atualizado com os últimos encontros).
Também acho que ninguém tenha intenções de ficar controlando muito o conteúdo do site.
A gente se manifesta porque a gente se importa, a Python Floripa faz parte da nossa história e vice-versa.

Confesso que também fiquei chateado em ver sumir o conteúdo que eu e outros tínhamos já investido bastante energia em colocar lá sem nenhum aviso prévio.
A maneira educada tradicionalmente de fazer esse tipo mudança grande nos projetos open source é abrir uma issue para discussão e dar um tempo para quem se importa se manifestar.
Teria sido um gesto de carinho e respeito pelo histórico, que acredito não seja desmerecido. :)


@mateusoliveira43 mano, histórico no Git é bom, mas é quase a mesma coisa que se tivesse apagado -- em efeitos práticos, a maior parte das pessoas nunca vai acessar. =)

Eu gostei da ideia do Rougeth do `v1.floripa`, mas caso for complicado de fazer ou caso preferirem evitar a confusão de ter 2 sites, não dá pra ao menos resgatar o conteúdo com o [histórico dos encontros](https://github.com/PythonFloripa/pythonfloripa.github.io/blob/327d782bf1499ca46942c97144927db4f34704e9/docs/encontros.md)?
Muitas vezes voltei pra essa página pra achar o link de uma das palestras.

Também achava super válido a lista de empresas da cidade usando Python, embora deve ter hoje muitas mais? =)

Amor e afeto a todos! <3

**Comment by rougeth** [comment]
@eliasdorneles subi o site antigo no endereço http://floripa.sc.python.org.br/v1/ e o @mateusoliveira43 ficou de adicionar os links enquanto o conteúdo não for migrado.

**Comment by rougeth** [comment]
@ssjunior

Iniciei meu comentário concordando com a importância do histórico, reli algumas vezes mas não sei como pode ter sido interpretado de outra forma. Minha discordância em seu comentário foi na necessidade de envolver pessoas que já não participam mais da organização ou da comunidade nas mudanças. Você comentou isso, envolver "quem tem histórico ou apenas um sentimento nostálgico". Acho isso impraticável. Vale ressaltar que a mudança pode não ter sido feita de forma individual ou sem discussão com outros membros (Matheus pode dar mais detalhes se fizer sentido).

Importantíssimo o papel de quem organizou os primeiros encontros, quem levou a pizza, o chopp e os salgadinhos. Mas não mais importante que as pessoas que vieram depois, quem gerenciou os meetups, quem foi atrás das empresas para patrocínio, quem moderou os grupos no Telegram, etc. Não há comunidade sem quem veio antes, nem depois. E é essa a beleza, a força está no grupo, não no indivíduo ;)

**Comment by mateusoliveira43** [comment]
Oi pessoal, vou colocar um link no site novo levando ao antigo, que o Marco colocou no ar, aí linko PR nessa issue.

Em nenhum momento foi uma atitude individual... fiquei chateado de não terem falado nada antes, porque venho falando do assunto a algum tempo no telegram da organização (nem passou na minha cabeça abrir uma issue aqui kkkkk), então achei que não tinha problema algum a atualização (que ainda está em andamento e deve levar um tempinho kkkkk), mas em contrapartida, fico feliz de ter tanta gente que quer contribuir pra não se perder a info antiga!

Para evitar no futuro problema semelhante, que tal escrevemos na [wiki do repo](https://github.com/PythonFloripa/pythonfloripa.github.io/wiki) algumas dicas sobre transições? (é markdown pra editar, bem simples, aí só adicionar a página na barra lateral) Peço também que criem sugestões e o que querem ver no site novo seguindo o [guia](https://github.com/PythonFloripa/pythonfloripa.github.io/blob/development/docs/CONTRIBUTING.md) (fiquem a vontade para sugerir melhorias na organização do repo, wiki e guias!)

**Comment by apast** [comment]
Olá, pessoal,

Compreendo que muito da discussão nesta issue é resultado de um problema de comunicação sobre as ações tomadas em um dos canais mais importantes da comunidade, que é o site.

Como um dos objetivos é tornar a evolução pública e envolver mais pessoas, talvez as mudanças possam ser comunicadas no próprio canal da comunidade no Telegram.

Por exemplo, ao abrir um Pull Request importante, como a substituição de um site inteiro por um novo, comunicar no canal pode ser uma maneira de tornar o conhecimento público e aberto a discussões positivas. Uma mensagem como "Pessoal, novas mudanças no site. A contribuição das pessoas da comunidade será muito importante. Aberto a sugestões. <link do PR>"

O "canal da organização" da comunidade possui um número restrito de pessoas e não é a melhor forma de integrar novas idéias. Pessoas que já organizaram eventos anteriores, contribuiram e contribuem de muitas maneiras na evolução da Comunidade e conhecem a importância dela, não estão presentes neste canal, principalmente por ser fechado e praticamente desconhecido.

Recomendo a maior parte das discussões serem abertas no [canal oficial e principal](https://t.me/pythonfloripa).

Restringir a comunicação exclui e transmite a mensagem que algumas pessoas podem agir e outras não, principalmente não sendo esta uma característica da comunidade formada por pessoas voluntárias.

Dentre os assuntos a serem abertos, estão:
- Organização das edições dos eventos (presenciais e online);
- Mudanças e Propostas de melhorias para a comunidade.

Se alguma discussão mais complexa, pode-se abrir issues ou gists gerais no github, ou por qualquer outro meio público adequado. Inclusive, discutir o melhor meio faz parte de uma discussão aberta. O canal no telegram pode ser um dos melhores lugares para se iniciar!

Comunicação aberta permite mais diversidade de idéias, não exclui pessoas que poderiam contribuir, ensina novas pessoas a compreenderem como as decisões são tomadas, torna o ambiente seguro e confortável, reduz barreiras para contribuição na "organização".

Um abraço a todas as pessoas!

**Comment by mateusoliveira43** [comment]
Acho uma boa usar mais o telegram mesmo!

**Comment by rafaelcalixto** [comment]
Olá pessoal, desculpem a demora para me pronunciar sobre o assunto, mas tenho andado bem enrolado com o fim do semestre no meu mestrado.<br />
    Primeiramente, dou os parabéns ao @mateusoliveira43 mais uma vez pela ideia de atualizar o site da comunidade Python Floripa. Desde que ele colocou esta ideia eu tenho incentivado ele a fazer o que considero um dos valores mais importantes desde que entrei na organização da Python Floripa; ser transparente nas discussões e decisões que tomamos. Por isso, abrimos este tópico para discussão no grupo da Organização da Python Floripa, no grupo geral da Python Floripa e nos nossos encontros mensais da comunidade. <br />
    Desde que entramos para a organização da comunidade, não tivemos acesso ou soubemos da existência de nenhuma documentação orientando sobre nenhum processo definido pela comunidade (tanto com relação ao site como no geral), por isso, considero que argumentar que deveria ser utilizado um meio específico de abertura de debate como abrir uma RFC aqui é, no mínimo, injusto (até porque estaríamos excluindo do debate quem não é desenvolvedor). Abrimos o tópico para discussão nos principais canais da comunidade e acredito que fizemos o possível para ser o mais transparente possível.<br />
    Quanto ao conteúdo histórico, nunca tivemos a intensão de apagar definitivamente. A ideia era COMEÇAR um novo site onde pudéssemos construir o conteúdo de forma coletiva. Nesse sentido, gostaria de contar com a ajuda dos integrantes mais antigos da comunidade @eliasdorneles @ssjunior para migrar o conteúdo histórico para o novo site. Repito, nunca tivemos a ideia de apagar nada e sim de realizar uma nova construção coletiva.<br />
    Quero também deixar registrado também que uma das grandes motivações para fazermos um novo site é documentar todo o processo para que as próximas gerações de organizadores da comunidade Python Floripa tenham um suporte para seguir com as atividades da comunidade, pois o maior desafio que eu tenho encontrado desde que entrei para a organização tem sido encontrar informações relativas aos processos e atividades que eram realizadas anteriormente.<br />
    Por fim, desejo que este tópico de discussão sirva para reaproximar as diferentes gerações de organizadores da Python Floripa e não para separar ainda mais.<br />
Grande abraço à todos.

**Comment by mateusoliveira43** [comment]
@eliasdorneles @ssjunior e @apast 

Além do PR https://github.com/PythonFloripa/pythonfloripa.github.io/pull/51 criei essa página na wiki https://github.com/PythonFloripa/pythonfloripa.github.io/wiki/História para evitar problemas futuros. 

Com isso, podemos fechar o PR e consequentemente essa issue?

**Comment by ssjunior** [comment]
@mateusoliveira43 @rafaelcalixto 

Obrigado pela preocupação em nos manter informado. Gostaria de dar algumas sugestões:

1 - Colocar no site links para os endereços onde existem discussões (telegram, fb, twitter..) explicando como se 'encontram' as pessoas. Se não fosse o And, não teria como saber da existência do canal do Telegram. Isso é importante para direcionar as pessoas para onde as conversas acontecem e mostrar o que já foi feito ou o que está por vir.

O @rafaelcalixto citou acima: 'grupo da Organização da Python Floripa, no grupo geral da Python Floripa e nos nossos encontros mensais da comunidade.' Seria muito bom colocar no site como encontramos estes grupos e onde estão informações dos mesmos. Assim todo novo participante poderiam ser guiado neste integração.

2 - Na minha visão toda alteração do site deve ser uma evolução, ou seja, pode-se alterar o design, acrescentar conteúdo, mas, sempre mantendo o conteúdo que já existe. Não faz muito sentido ter que clicar num link para ver uma versão antiga, para descobrir o conteúdo que está lá. Na prática ninguém faz isso. Deve existir um senso de continuidade e não de disrupção. Imagine que o que você está fazendo agora vai ter todo o conteúdo removido por causa de uma nova versão. E não digo isso por apelo emocional, e sim apenas pq 'content is king' e o mesmo deve sempre ter fácil acesso.. Eu pessoalmente, em tudo que acesso gosto de ver a história e entender a dinâmica das coisas. Pensa em como você gosta de ver as coisas...

O site deve ser um organismo vivo e como tal deve ir evoluindo, integrando conteúdo e exibindo o mesmo de forma amigável e com usabilidade. 

São meus 2 cents. Dito isso encerro por aqui minha participação. Pode fechar a issue e dar continuidade do jeito que julgarem mais adequado.

Abs.

**Comment by eliasdorneles** [comment]
Olá pessoal!

Acho que pedir que sempre se mantenha inteiramente as versões anteriores do site no ar é desnecessário e oneroso: concordo com o @ssjunior, o conteúdo que é importante.
Em geral, quando se trata de migração de site, se faz um plano para migrar o conteúdo, que pode até incluir atenção para que URLs de páginas anteriores funcionem.
Mas fiquem à vontade para decidirem o que ficar melhor/mais simples.

Meu desejo abrindo esse ticket era ter o conteúdo antigo mais relevante disponível em algum lugar de fácil acesso, ou um plano pra ter o conteúdo migrado: considero que já está contemplado, obrigado pour ouvirem! <3
Por mim pode fechar o ticket, sem medo! :)

Obrigado!

**Comment by mateusoliveira43** [comment]
Beleza! 

Vamos colocar links para todas as redes sociais sim, pretendo fazer isso semana que vem no máximo.

Hmm boa colocação, apelei mais pro emocional no link pro site antigo, acho que vale pensar isso melhor, mas até ter o conteúdo ser migrado, mantemos ele!
