### ISSUE TITLE
Branch principal

### ISSUE THREAD

**Issue by feliperuhland** [PythonFloripa/pythonfloripa.github.io#8]
@jairojair podes alterar a branch principal para a `development`?

**Comment by jairojair** [comment]
já alterei @feliperuhland mas  você não tem permissão ?

**Comment by feliperuhland** [comment]
Ao `settings` do repositório não. Tenho permissão de leitura e escrita.
Valeu @jairojair

**Comment by jairojair** [comment]
já liberei acesso full @feliperuhland  Abraço

**Comment by feliperuhland** [comment]
Obrigado @jairojair !
